language: node_js

node_js:
  - "10.6.0"

cache:
  directories:
    - "node_modules"

install: npm ci || npm i

after_script: git diff --quiet || (git add . && git commit -m "Updated the lockfile" && git push)
