language: node_js

node_js:
  - "10.6.0"

cache:
  directories:
    - "node_modules"

before_install: npm i -g greenkeeper-lockfile; greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload
